/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Tax212
 * API pro správu a synchronizaci investičního portfolia z Trading212
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AccountSummaryDto,
  ApiErrorResponse,
  GetDividendsParams,
  GetPortfolioParams,
  GetTransactionsParams,
  PagedResponseDividendDto,
  PagedResponseTransactionDto,
  PortfolioStatusDto,
  TaxReportDto,
  ValidationErrorResponse
} from './model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type syncTransactionsResponse200 = {
  data: void
  status: 200
}

export type syncTransactionsResponse400 = {
  data: void
  status: 400
}

export type syncTransactionsResponse401 = {
  data: void
  status: 401
}

export type syncTransactionsResponse403 = {
  data: void
  status: 403
}

export type syncTransactionsResponse408 = {
  data: void
  status: 408
}

export type syncTransactionsResponse429 = {
  data: void
  status: 429
}

export type syncTransactionsResponse500 = {
  data: void
  status: 500
}

export type syncTransactionsResponseSuccess = (syncTransactionsResponse200) & {
  headers: Headers;
};
export type syncTransactionsResponseError = (syncTransactionsResponse400 | syncTransactionsResponse401 | syncTransactionsResponse403 | syncTransactionsResponse408 | syncTransactionsResponse429 | syncTransactionsResponse500) & {
  headers: Headers;
};

export type syncTransactionsResponse = (syncTransactionsResponseSuccess | syncTransactionsResponseError)

export const getSyncTransactionsUrl = () => {




  return `http://localhost:8080/api/sync/transactions`
}

/**
 * Aktualizuje seznam transakcí od posledního známého stavu.
 * @summary Synchronizace transakcí
 */
export const syncTransactions = async ( options?: RequestInit): Promise<syncTransactionsResponse> => {

  const res = await fetch(getSyncTransactionsUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: syncTransactionsResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as syncTransactionsResponse
}





export const getSyncTransactionsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncTransactions>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof syncTransactions>>, TError,void, TContext> => {

const mutationKey = ['syncTransactions'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncTransactions>>, void> = () => {


          return  syncTransactions(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SyncTransactionsMutationResult = NonNullable<Awaited<ReturnType<typeof syncTransactions>>>

    export type SyncTransactionsMutationError = void

    /**
 * @summary Synchronizace transakcí
 */
export const useSyncTransactions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncTransactions>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof syncTransactions>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSyncTransactionsMutationOptions(options), queryClient);
    }

export type performFullSyncResponse200 = {
  data: void
  status: 200
}

export type performFullSyncResponse400 = {
  data: void
  status: 400
}

export type performFullSyncResponse401 = {
  data: void
  status: 401
}

export type performFullSyncResponse403 = {
  data: void
  status: 403
}

export type performFullSyncResponse408 = {
  data: void
  status: 408
}

export type performFullSyncResponse429 = {
  data: void
  status: 429
}

export type performFullSyncResponse500 = {
  data: void
  status: 500
}

export type performFullSyncResponseSuccess = (performFullSyncResponse200) & {
  headers: Headers;
};
export type performFullSyncResponseError = (performFullSyncResponse400 | performFullSyncResponse401 | performFullSyncResponse403 | performFullSyncResponse408 | performFullSyncResponse429 | performFullSyncResponse500) & {
  headers: Headers;
};

export type performFullSyncResponse = (performFullSyncResponseSuccess | performFullSyncResponseError)

export const getPerformFullSyncUrl = () => {




  return `http://localhost:8080/api/sync/full`
}

/**
 * Spustí proces úplné aktualizace dat. Zahrnuje informace o účtu, portfoliu i celou historii transakcí.
 * @summary Kompletní synchronizace
 */
export const performFullSync = async ( options?: RequestInit): Promise<performFullSyncResponse> => {

  const res = await fetch(getPerformFullSyncUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: performFullSyncResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as performFullSyncResponse
}





export const getPerformFullSyncMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof performFullSync>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof performFullSync>>, TError,void, TContext> => {

const mutationKey = ['performFullSync'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof performFullSync>>, void> = () => {


          return  performFullSync(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PerformFullSyncMutationResult = NonNullable<Awaited<ReturnType<typeof performFullSync>>>

    export type PerformFullSyncMutationError = void

    /**
 * @summary Kompletní synchronizace
 */
export const usePerformFullSync = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof performFullSync>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof performFullSync>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPerformFullSyncMutationOptions(options), queryClient);
    }

export type syncDividendsResponse200 = {
  data: void
  status: 200
}

export type syncDividendsResponse400 = {
  data: void
  status: 400
}

export type syncDividendsResponse401 = {
  data: void
  status: 401
}

export type syncDividendsResponse403 = {
  data: void
  status: 403
}

export type syncDividendsResponse408 = {
  data: void
  status: 408
}

export type syncDividendsResponse429 = {
  data: void
  status: 429
}

export type syncDividendsResponse500 = {
  data: void
  status: 500
}

export type syncDividendsResponseSuccess = (syncDividendsResponse200) & {
  headers: Headers;
};
export type syncDividendsResponseError = (syncDividendsResponse400 | syncDividendsResponse401 | syncDividendsResponse403 | syncDividendsResponse408 | syncDividendsResponse429 | syncDividendsResponse500) & {
  headers: Headers;
};

export type syncDividendsResponse = (syncDividendsResponseSuccess | syncDividendsResponseError)

export const getSyncDividendsUrl = () => {




  return `http://localhost:8080/api/sync/dividends`
}

/**
 * Aktualizuje seznam dividend od posledního známého stavu.
 * @summary Synchronizace dividend
 */
export const syncDividends = async ( options?: RequestInit): Promise<syncDividendsResponse> => {

  const res = await fetch(getSyncDividendsUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: syncDividendsResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as syncDividendsResponse
}





export const getSyncDividendsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncDividends>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof syncDividends>>, TError,void, TContext> => {

const mutationKey = ['syncDividends'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncDividends>>, void> = () => {


          return  syncDividends(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SyncDividendsMutationResult = NonNullable<Awaited<ReturnType<typeof syncDividends>>>

    export type SyncDividendsMutationError = void

    /**
 * @summary Synchronizace dividend
 */
export const useSyncDividends = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncDividends>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof syncDividends>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSyncDividendsMutationOptions(options), queryClient);
    }

export type syncAccountDetailsResponse200 = {
  data: void
  status: 200
}

export type syncAccountDetailsResponse400 = {
  data: void
  status: 400
}

export type syncAccountDetailsResponse401 = {
  data: void
  status: 401
}

export type syncAccountDetailsResponse403 = {
  data: void
  status: 403
}

export type syncAccountDetailsResponse408 = {
  data: void
  status: 408
}

export type syncAccountDetailsResponse429 = {
  data: void
  status: 429
}

export type syncAccountDetailsResponse500 = {
  data: void
  status: 500
}

export type syncAccountDetailsResponseSuccess = (syncAccountDetailsResponse200) & {
  headers: Headers;
};
export type syncAccountDetailsResponseError = (syncAccountDetailsResponse400 | syncAccountDetailsResponse401 | syncAccountDetailsResponse403 | syncAccountDetailsResponse408 | syncAccountDetailsResponse429 | syncAccountDetailsResponse500) & {
  headers: Headers;
};

export type syncAccountDetailsResponse = (syncAccountDetailsResponseSuccess | syncAccountDetailsResponseError)

export const getSyncAccountDetailsUrl = () => {




  return `http://localhost:8080/api/sync/account`
}

/**
 * Aktualizuje aktuální zůstatky, volnou hotovost a nastavení účtu.
 * @summary Synchronizace detailů účtu
 */
export const syncAccountDetails = async ( options?: RequestInit): Promise<syncAccountDetailsResponse> => {

  const res = await fetch(getSyncAccountDetailsUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: syncAccountDetailsResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as syncAccountDetailsResponse
}





export const getSyncAccountDetailsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncAccountDetails>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof syncAccountDetails>>, TError,void, TContext> => {

const mutationKey = ['syncAccountDetails'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncAccountDetails>>, void> = () => {


          return  syncAccountDetails(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SyncAccountDetailsMutationResult = NonNullable<Awaited<ReturnType<typeof syncAccountDetails>>>

    export type SyncAccountDetailsMutationError = void

    /**
 * @summary Synchronizace detailů účtu
 */
export const useSyncAccountDetails = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncAccountDetails>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof syncAccountDetails>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSyncAccountDetailsMutationOptions(options), queryClient);
    }

export type getTransactionsResponse200 = {
  data: PagedResponseTransactionDto
  status: 200
}

export type getTransactionsResponse400 = {
  data: ValidationErrorResponse
  status: 400
}

export type getTransactionsResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getTransactionsResponseSuccess = (getTransactionsResponse200) & {
  headers: Headers;
};
export type getTransactionsResponseError = (getTransactionsResponse400 | getTransactionsResponse500) & {
  headers: Headers;
};

export type getTransactionsResponse = (getTransactionsResponseSuccess | getTransactionsResponseError)

export const getGetTransactionsUrl = (params?: GetTransactionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["sort"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8080/api/transactions?${stringifiedParams}` : `http://localhost:8080/api/transactions`
}

/**
 * @summary Získá seznam transakcí s filtrací
 */
export const getTransactions = async (params?: GetTransactionsParams, options?: RequestInit): Promise<getTransactionsResponse> => {

  const res = await fetch(getGetTransactionsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getTransactionsResponse['data'] = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return { data, status: res.status, headers: res.headers } as getTransactionsResponse
}





export const getGetTransactionsQueryKey = (params?: GetTransactionsParams,) => {
    return [
    `http://localhost:8080/api/transactions`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetTransactionsQueryOptions = <TData = Awaited<ReturnType<typeof getTransactions>>, TError = ValidationErrorResponse | ApiErrorResponse>(params?: GetTransactionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTransactions>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTransactionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTransactions>>> = ({ signal }) => getTransactions(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTransactions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTransactionsQueryResult = NonNullable<Awaited<ReturnType<typeof getTransactions>>>
export type GetTransactionsQueryError = ValidationErrorResponse | ApiErrorResponse


export function useGetTransactions<TData = Awaited<ReturnType<typeof getTransactions>>, TError = ValidationErrorResponse | ApiErrorResponse>(
 params: undefined |  GetTransactionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTransactions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransactions>>,
          TError,
          Awaited<ReturnType<typeof getTransactions>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTransactions<TData = Awaited<ReturnType<typeof getTransactions>>, TError = ValidationErrorResponse | ApiErrorResponse>(
 params?: GetTransactionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTransactions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransactions>>,
          TError,
          Awaited<ReturnType<typeof getTransactions>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTransactions<TData = Awaited<ReturnType<typeof getTransactions>>, TError = ValidationErrorResponse | ApiErrorResponse>(
 params?: GetTransactionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTransactions>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Získá seznam transakcí s filtrací
 */

export function useGetTransactions<TData = Awaited<ReturnType<typeof getTransactions>>, TError = ValidationErrorResponse | ApiErrorResponse>(
 params?: GetTransactionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTransactions>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTransactionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getDividendsResponse200 = {
  data: PagedResponseDividendDto
  status: 200
}

export type getDividendsResponse400 = {
  data: ValidationErrorResponse
  status: 400
}

export type getDividendsResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getDividendsResponseSuccess = (getDividendsResponse200) & {
  headers: Headers;
};
export type getDividendsResponseError = (getDividendsResponse400 | getDividendsResponse500) & {
  headers: Headers;
};

export type getDividendsResponse = (getDividendsResponseSuccess | getDividendsResponseError)

export const getGetDividendsUrl = (params?: GetDividendsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["sort"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8080/api/dividends?${stringifiedParams}` : `http://localhost:8080/api/dividends`
}

/**
 * @summary Získá seznam dividend s filtrací
 */
export const getDividends = async (params?: GetDividendsParams, options?: RequestInit): Promise<getDividendsResponse> => {

  const res = await fetch(getGetDividendsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getDividendsResponse['data'] = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return { data, status: res.status, headers: res.headers } as getDividendsResponse
}





export const getGetDividendsQueryKey = (params?: GetDividendsParams,) => {
    return [
    `http://localhost:8080/api/dividends`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetDividendsQueryOptions = <TData = Awaited<ReturnType<typeof getDividends>>, TError = ValidationErrorResponse | ApiErrorResponse>(params?: GetDividendsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDividends>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDividendsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDividends>>> = ({ signal }) => getDividends(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDividends>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDividendsQueryResult = NonNullable<Awaited<ReturnType<typeof getDividends>>>
export type GetDividendsQueryError = ValidationErrorResponse | ApiErrorResponse


export function useGetDividends<TData = Awaited<ReturnType<typeof getDividends>>, TError = ValidationErrorResponse | ApiErrorResponse>(
 params: undefined |  GetDividendsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDividends>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDividends>>,
          TError,
          Awaited<ReturnType<typeof getDividends>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDividends<TData = Awaited<ReturnType<typeof getDividends>>, TError = ValidationErrorResponse | ApiErrorResponse>(
 params?: GetDividendsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDividends>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDividends>>,
          TError,
          Awaited<ReturnType<typeof getDividends>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDividends<TData = Awaited<ReturnType<typeof getDividends>>, TError = ValidationErrorResponse | ApiErrorResponse>(
 params?: GetDividendsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDividends>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Získá seznam dividend s filtrací
 */

export function useGetDividends<TData = Awaited<ReturnType<typeof getDividends>>, TError = ValidationErrorResponse | ApiErrorResponse>(
 params?: GetDividendsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDividends>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDividendsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getYearlyReportResponse200 = {
  data: TaxReportDto
  status: 200
}

export type getYearlyReportResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getYearlyReportResponseSuccess = (getYearlyReportResponse200) & {
  headers: Headers;
};
export type getYearlyReportResponseError = (getYearlyReportResponse500) & {
  headers: Headers;
};

export type getYearlyReportResponse = (getYearlyReportResponseSuccess | getYearlyReportResponseError)

export const getGetYearlyReportUrl = (year: number,) => {




  return `http://localhost:8080/api/accounts/tax-reports/${year}`
}

/**
 * Vypočítá sumární hodnoty prodejů rozdělené na ty, které splňují časový test pro osvobození od daně, a ty, které podléhají zdanění.
 * @summary Generovat roční daňový report
 */
export const getYearlyReport = async (year: number, options?: RequestInit): Promise<getYearlyReportResponse> => {

  const res = await fetch(getGetYearlyReportUrl(year),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getYearlyReportResponse['data'] = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return { data, status: res.status, headers: res.headers } as getYearlyReportResponse
}





export const getGetYearlyReportQueryKey = (year: number,) => {
    return [
    `http://localhost:8080/api/accounts/tax-reports/${year}`
    ] as const;
    }


export const getGetYearlyReportQueryOptions = <TData = Awaited<ReturnType<typeof getYearlyReport>>, TError = ApiErrorResponse>(year: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getYearlyReport>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetYearlyReportQueryKey(year);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getYearlyReport>>> = ({ signal }) => getYearlyReport(year, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: year !== null && year !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getYearlyReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetYearlyReportQueryResult = NonNullable<Awaited<ReturnType<typeof getYearlyReport>>>
export type GetYearlyReportQueryError = ApiErrorResponse


export function useGetYearlyReport<TData = Awaited<ReturnType<typeof getYearlyReport>>, TError = ApiErrorResponse>(
 year: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getYearlyReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getYearlyReport>>,
          TError,
          Awaited<ReturnType<typeof getYearlyReport>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetYearlyReport<TData = Awaited<ReturnType<typeof getYearlyReport>>, TError = ApiErrorResponse>(
 year: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getYearlyReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getYearlyReport>>,
          TError,
          Awaited<ReturnType<typeof getYearlyReport>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetYearlyReport<TData = Awaited<ReturnType<typeof getYearlyReport>>, TError = ApiErrorResponse>(
 year: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getYearlyReport>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Generovat roční daňový report
 */

export function useGetYearlyReport<TData = Awaited<ReturnType<typeof getYearlyReport>>, TError = ApiErrorResponse>(
 year: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getYearlyReport>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetYearlyReportQueryOptions(year,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getSummaryResponse200 = {
  data: AccountSummaryDto
  status: 200
}

export type getSummaryResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getSummaryResponseSuccess = (getSummaryResponse200) & {
  headers: Headers;
};
export type getSummaryResponseError = (getSummaryResponse500) & {
  headers: Headers;
};

export type getSummaryResponse = (getSummaryResponseSuccess | getSummaryResponseError)

export const getGetSummaryUrl = () => {




  return `http://localhost:8080/api/accounts/summary`
}

/**
 * Vrátí celkový finanční přehled investičního účtu včetně zisků, ztrát a nákladů.
 * @summary Získat souhrn účtu
 */
export const getSummary = async ( options?: RequestInit): Promise<getSummaryResponse> => {

  const res = await fetch(getGetSummaryUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getSummaryResponse['data'] = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return { data, status: res.status, headers: res.headers } as getSummaryResponse
}





export const getGetSummaryQueryKey = () => {
    return [
    `http://localhost:8080/api/accounts/summary`
    ] as const;
    }


export const getGetSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getSummary>>, TError = ApiErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSummaryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSummary>>> = ({ signal }) => getSummary({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getSummary>>>
export type GetSummaryQueryError = ApiErrorResponse


export function useGetSummary<TData = Awaited<ReturnType<typeof getSummary>>, TError = ApiErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSummary>>,
          TError,
          Awaited<ReturnType<typeof getSummary>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSummary<TData = Awaited<ReturnType<typeof getSummary>>, TError = ApiErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSummary>>,
          TError,
          Awaited<ReturnType<typeof getSummary>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSummary<TData = Awaited<ReturnType<typeof getSummary>>, TError = ApiErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Získat souhrn účtu
 */

export function useGetSummary<TData = Awaited<ReturnType<typeof getSummary>>, TError = ApiErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSummaryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getPortfolioResponse200 = {
  data: PortfolioStatusDto
  status: 200
}

export type getPortfolioResponse500 = {
  data: ApiErrorResponse
  status: 500
}

export type getPortfolioResponseSuccess = (getPortfolioResponse200) & {
  headers: Headers;
};
export type getPortfolioResponseError = (getPortfolioResponse500) & {
  headers: Headers;
};

export type getPortfolioResponse = (getPortfolioResponseSuccess | getPortfolioResponseError)

export const getGetPortfolioUrl = (params?: GetPortfolioParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8080/api/accounts/portfolio?${stringifiedParams}` : `http://localhost:8080/api/accounts/portfolio`
}

/**
 * Vrátí seznam držených aktiv k určenému datu. Pokud datum není zadáno, vrátí aktuální stav. Výpočet zohledňuje časový test pro daňové účely.
 * @summary Získat stav portfolia
 */
export const getPortfolio = async (params?: GetPortfolioParams, options?: RequestInit): Promise<getPortfolioResponse> => {

  const res = await fetch(getGetPortfolioUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getPortfolioResponse['data'] = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return { data, status: res.status, headers: res.headers } as getPortfolioResponse
}





export const getGetPortfolioQueryKey = (params?: GetPortfolioParams,) => {
    return [
    `http://localhost:8080/api/accounts/portfolio`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetPortfolioQueryOptions = <TData = Awaited<ReturnType<typeof getPortfolio>>, TError = ApiErrorResponse>(params?: GetPortfolioParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPortfolio>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPortfolioQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPortfolio>>> = ({ signal }) => getPortfolio(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPortfolio>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPortfolioQueryResult = NonNullable<Awaited<ReturnType<typeof getPortfolio>>>
export type GetPortfolioQueryError = ApiErrorResponse


export function useGetPortfolio<TData = Awaited<ReturnType<typeof getPortfolio>>, TError = ApiErrorResponse>(
 params: undefined |  GetPortfolioParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPortfolio>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPortfolio>>,
          TError,
          Awaited<ReturnType<typeof getPortfolio>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPortfolio<TData = Awaited<ReturnType<typeof getPortfolio>>, TError = ApiErrorResponse>(
 params?: GetPortfolioParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPortfolio>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPortfolio>>,
          TError,
          Awaited<ReturnType<typeof getPortfolio>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPortfolio<TData = Awaited<ReturnType<typeof getPortfolio>>, TError = ApiErrorResponse>(
 params?: GetPortfolioParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPortfolio>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Získat stav portfolia
 */

export function useGetPortfolio<TData = Awaited<ReturnType<typeof getPortfolio>>, TError = ApiErrorResponse>(
 params?: GetPortfolioParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPortfolio>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPortfolioQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







