spring:
  datasource:
    url: jdbc:sqlite:tax212.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /v3/api-docs
trading212:
  api:
    url: https://live.trading212.com/api/v0
    username: ${T212_KEY_ID}
    password: ${T212_KEY_SECRET}
tax:
  limits:
    asset-sale-annual-cap: 100000
    incidental-income-cap: 20000
    holding-period-years: 3