/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Tax212
 * API pro správu a synchronizaci investičního portfolia z Trading212
 * OpenAPI spec version: 1.0
 */

/**
 * Finanční souhrn investičního portfolia
 */
export interface AccountSummaryDto {
  /** Kód měny účtu */
  currency?: string;
  /** Celková hodnota majetku (aktuální cena aktiv + hotovost) */
  totalValue?: number;
  /** Aktuální tržní hodnota držených pozic */
  currentValue?: number;
  /** Celkové historické náklady na pořízení (nákupní ceny) */
  totalCost?: number;
  /** Skutečný realizovaný zisk nebo ztráta (z uzavřených obchodů) */
  actualRealizedProfitLoss?: number;
  /** Realizovaný zisk nebo ztráta (z uzavřených obchodů) */
  realizedProfitLoss?: number;
  /** Nerealizovaný (papírový) zisk nebo ztráta (rozdíl tržní ceny a nákladů) */
  unrealizedProfitLoss?: number;
}
