/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Tax212
 * API pro správu a synchronizaci investičního portfolia z Trading212
 * OpenAPI spec version: 1.0
 */
import type { DividendDtoType } from './dividendDtoType';
import type { InstrumentDto } from './instrumentDto';

/**
 * Informace o vyplacené dividendě
 */
export interface DividendDto {
  /** Interní databázové ID záznamu */
  id?: number;
  /** Unikátní ID transakce z Trading 212 (reference) */
  t212id?: string;
  /** Ticker symbol instrumentu */
  ticker?: string;
  /** Datum a čas připsání dividendy na účet */
  paidOn?: string;
  /** Čistá částka dividendy v primární měně účtu */
  amount?: number;
  /** Čistá částka dividendy přepočtená na EUR */
  amountInEuro?: number;
  /** Kód primární měny účtu */
  currency?: string;
  /** Hrubá výše dividendy na jednu akcii v měně instrumentu */
  grossAmountPerShare?: number;
  /** Počet držených kusů (včetně frakcí) v rozhodný den */
  quantity?: number;
  /** Typ dividendové události */
  type?: DividendDtoType;
  /** Detailní informace o akcii, ke které se dividenda váže */
  instrument?: InstrumentDto;
}
