/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Tax212
 * API pro správu a synchronizaci investičního portfolia z Trading212
 * OpenAPI spec version: 1.0
 */

/**
 * Detail konkrétního nevalidního pole
 */
export interface FieldErrorDetail {
  field?: string;
  message?: string;
}
