/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Tax212
 * API pro správu a synchronizaci investičního portfolia z Trading212
 * OpenAPI spec version: 1.0
 */

export type GetDividendsParams = {
/**
 * Ticker symbol instrumentu
 * @minLength 1
 * @maxLength 20
 */
ticker?: string;
/**
 * Datum od (včetně) ve formátu YYYY-MM-DD
 */
dateFrom?: string;
/**
 * Datum do (včetně) ve formátu YYYY-MM-DD
 */
dateTo?: string;
/**
 * Mezinárodní identifikační číslo ISIN
 * @minLength 12
 * @maxLength 12
 */
isin?: string;
/**
 * Název instrumentu (vyhledávání like)
 * @minLength 2
 * @maxLength 2147483647
 */
instrumentName?: string;
/**
 * Číslo stránky (od 0)
 * @minimum 0
 */
page?: number;
/**
 * Počet prvků na stránku (1-100)
 * @minimum 1
 * @maximum 100
 */
size?: number;
sort?: string[];
};
