/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Tax212
 * API pro správu a synchronizaci investičního portfolia z Trading212
 * OpenAPI spec version: 1.0
 */

export type GetPortfolioParams = {
/**
 * Datum a čas, ke kterému se má stav portfolia vypočítat. Formát ISO
 */
date?: string;
/**
 * Zahrnout prodaná aktiva
 */
includeSold?: boolean;
};
