/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Tax212
 * API pro správu a synchronizaci investičního portfolia z Trading212
 * OpenAPI spec version: 1.0
 */

export type GetTransactionsSide = typeof GetTransactionsSide[keyof typeof GetTransactionsSide];


export const GetTransactionsSide = {
  BUY: 'BUY',
  SELL: 'SELL',
} as const;
