/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Tax212
 * API pro správu a synchronizaci investičního portfolia z Trading212
 * OpenAPI spec version: 1.0
 */

/**
 * Základní identifikace finančního nástroje (akcie, ETF apod.)
 */
export interface InstrumentDto {
  /** Burzovní symbol (ticker) */
  ticker?: string;
  /** Čistý tržní symbol */
  marketTicker?: string;
  /** Celý název instrumentu */
  name?: string;
  /** Mezinárodní identifikační číslo cenného papíru */
  isin?: string;
  /** Obchodní měna instrumentu */
  currency?: string;
}
