/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Tax212
 * API pro správu a synchronizaci investičního portfolia z Trading212
 * OpenAPI spec version: 1.0
 */
import type { TransactionDto } from './transactionDto';

export interface PagedResponseTransactionDto {
  page?: number;
  totalPages?: number;
  pageSize?: number;
  numberOfItems?: number;
  totalItems?: number;
  sort?: string[];
  items?: TransactionDto[];
}
