/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Tax212
 * API pro správu a synchronizaci investičního portfolia z Trading212
 * OpenAPI spec version: 1.0
 */
import type { InstrumentDto } from './instrumentDto';

/**
 * Detailní stav konkrétního aktiva v portfoliu
 */
export interface PortfolioStatusItemDto {
  /** Počet let pro splnění časového testu (typicky 3 roky v ČR) */
  timeTestYears?: number;
  /** Burzovní symbol aktiva */
  ticker?: string;
  /** Detailní informace o instrumentu */
  instrument?: InstrumentDto;
  /** Celkové aktuálně držené množství */
  availableQuantity?: number;
  /** Množství, které již splnilo časový test a je osvobozeno od daně (k danému datu) */
  taxFreeQuantity?: number;
  /** Množství, které je stále v daňovém testu (k danému datu) */
  inTaxQuantity?: number;
  /** Celkové historicky nakoupené množství */
  totalBuysQuantity?: number;
  /** Celkové historicky prodané množství */
  totalSellsQuantity?: number;
  /** Průměrná nákupní cena držených akcií */
  averageBuyPrice?: number;
  /** Průměrná prodejní cena */
  averageSellPrice?: number;
  /** Celkové historické náklady na nákupy */
  totalBuyCost?: number;
  /** Celková historická utržená hodnota z prodejů */
  totalSellValue?: number;
  /** Realizovaný zisk nebo ztráta z prodejů */
  realisedGainLoss?: number;
  /** Skutečný realizovaný zisk nebo ztráta z prodejů (očištěno od FX poplatku) */
  actualRealisedGainLoss?: number;
  /** Rozdíl mezi průměrným prodejem a nákupem (v %) */
  realizedGainLossPercent?: number;
  /** Skutečný rozdíl mezi průměrným prodejem a nákupem (v %), očištěno od FX poplatku */
  actualRealizedGainLossPercent?: number;
  /** Celková nákupní hodnota držených pozic v CZK */
  totalHoldingsCost?: number;
}
