/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Tax212
 * API pro správu a synchronizaci investičního portfolia z Trading212
 * OpenAPI spec version: 1.0
 */
import type { PortfolioStatusItemDto } from './portfolioStatusItemDto';

/**
 * Stav portfolia
 */
export interface PortfolioStatusDto {
  /** Doba časového testu */
  holdingPeriodYears?: number;
  /** Roční limit prodeje aktiv */
  assetSaleAnnualCap?: number;
  /** Roční limit okamžitých příjmů */
  incidentalIncomeCap?: number;
  /** Seznam aktiv v portfoliu a jejich stav */
  items?: PortfolioStatusItemDto[];
}
