/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Tax212
 * API pro správu a synchronizaci investičního portfolia z Trading212
 * OpenAPI spec version: 1.0
 */
import type { DividendDto } from './dividendDto';
import type { TransactionDto } from './transactionDto';

/**
 * Souhrnný daňový podklad pro konkrétní kalendářní rok
 */
export interface TaxReportDto {
  /** Reportovaný kalendářní rok */
  year?: number;
  /** Celková hodnota prodejů osvobozených od daně (splněn časový test 3 roky) */
  totalSoldTaxFree?: number;
  /** Celková hodnota zdanitelných prodejů (držené méně než 3 roky) */
  totalSoldTaxable?: number;
  /** Celková hrubá výše přijatých dividend v CZK (před zdaněním v zahraničí) */
  totalDividendsPaid?: number;
  /** Seznam všech realizovaných prodejních transakcí v daném roce */
  transactions?: TransactionDto[];
  /** Seznam všech přijatých dividend v daném roce */
  dividends?: DividendDto[];
}
