/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Tax212
 * API pro správu a synchronizaci investičního portfolia z Trading212
 * OpenAPI spec version: 1.0
 */
import type { InstrumentDto } from './instrumentDto';
import type { TransactionDtoFillType } from './transactionDtoFillType';
import type { TransactionDtoOrderStatus } from './transactionDtoOrderStatus';
import type { TransactionDtoSide } from './transactionDtoSide';

/**
 * Informace o konkrétní provedené obchodní transakci (nákup/prodej)
 */
export interface TransactionDto {
  /** Interní databázové ID záznamu */
  id?: number;
  /** Unikátní identifikátor transakce z platformy Trading 212 */
  t212id?: string;
  /** Identifikátor cenného papíru (Ticker) */
  ticker?: string;
  /** Směr transakce (BUY pro nákup, SELL pro prodej) */
  side?: TransactionDtoSide;
  /** Počet zobchodovaných kusů */
  quantity?: number;
  /** Realizovaná cena za jeden kus v měně instrumentu */
  price?: number;
  /** Použitý směnný kurz mezi měnou instrumentu a měnou účtu */
  fxRate?: number;
  /** Celková čistá hodnota transakce v měně účtu */
  walletImpact?: number;
  /** Reálná hodnota transakce */
  tradeValue?: number;
  /** Datum a čas vyplnění (provedení) objednávky na burze */
  filledAt?: string;
  /** Realizovaný zisk nebo ztráta podle Trading212 */
  tradingPnl?: number;
  /** Skutečný realizovaný zisk nebo ztráta (očištěno od FX poplatku) */
  actualPnl?: number;
  /** Status objednávky (např. FILLED) */
  orderStatus?: TransactionDtoOrderStatus;
  /** Typ provedení (např. TRADE, STOCK_SPLIT, FOP) */
  fillType?: TransactionDtoFillType;
  /** Detailní informace o souvisejícím instrumentu */
  instrument?: InstrumentDto;
}
