/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Tax212
 * API pro správu a synchronizaci investičního portfolia z Trading212
 * OpenAPI spec version: 1.0
 */

/**
 * Typ provedení (např. TRADE, STOCK_SPLIT, FOP)
 */
export type TransactionDtoFillType = typeof TransactionDtoFillType[keyof typeof TransactionDtoFillType];


export const TransactionDtoFillType = {
  TRADE: 'TRADE',
  STOCK_SPLIT: 'STOCK_SPLIT',
  STOCK_DISTRIBUTION: 'STOCK_DISTRIBUTION',
  FOP: 'FOP',
  FOP_CORRECTION: 'FOP_CORRECTION',
  CUSTOM_STOCK_DISTRIBUTION: 'CUSTOM_STOCK_DISTRIBUTION',
  EQUITY_RIGHTS: 'EQUITY_RIGHTS',
  SCRIP_STOCK_DIVIDENDS: 'SCRIP_STOCK_DIVIDENDS',
  STOCK_DIVIDENDS: 'STOCK_DIVIDENDS',
  STOCK_ACQUISITION: 'STOCK_ACQUISITION',
  CASH_AND_STOCK_ACQUISITION: 'CASH_AND_STOCK_ACQUISITION',
  SPIN_OFF: 'SPIN_OFF',
} as const;
