/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Tax212
 * API pro správu a synchronizaci investičního portfolia z Trading212
 * OpenAPI spec version: 1.0
 */

/**
 * Směr transakce (BUY pro nákup, SELL pro prodej)
 */
export type TransactionDtoSide = typeof TransactionDtoSide[keyof typeof TransactionDtoSide];


export const TransactionDtoSide = {
  BUY: 'BUY',
  SELL: 'SELL',
} as const;
