/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Tax212
 * API pro správu a synchronizaci investičního portfolia z Trading212
 * OpenAPI spec version: 1.0
 */

/**
 * Status objednávky (např. FILLED)
 */
export type TransactionDtoOrderStatus = typeof TransactionDtoOrderStatus[keyof typeof TransactionDtoOrderStatus];


export const TransactionDtoOrderStatus = {
  LOCAL: 'LOCAL',
  UNCONFIRMED: 'UNCONFIRMED',
  CONFIRMED: 'CONFIRMED',
  NEW: 'NEW',
  CANCELLING: 'CANCELLING',
  CANCELLED: 'CANCELLED',
  PARTIALLY_FILLED: 'PARTIALLY_FILLED',
  FILLED: 'FILLED',
  REJECTED: 'REJECTED',
  REPLACING: 'REPLACING',
  REPLACED: 'REPLACED',
} as const;
