/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Tax212
 * API pro správu a synchronizaci investičního portfolia z Trading212
 * OpenAPI spec version: 1.0
 */
import type { FieldErrorDetail } from './fieldErrorDetail';

/**
 * Detailní informace o chybách ve validaci polí
 */
export interface ValidationErrorResponse {
  /** HTTP stavový kód */
  status?: number;
  /** Detailní popis chyby */
  message?: string;
  /** Relativní cesta k endpointu, který chybu vyvolal */
  path?: string;
  /** Časový razítko vzniku chyby */
  timestamp?: string;
  /** Seznam konkrétních chyb na úrovni polí */
  errors?: FieldErrorDetail[];
}
