package eu.tmach.trading212.model;

public enum FillType {
    TRADE,
    STOCK_SPLIT,
    STOCK_DISTRIBUTION,
    FOP,
    FOP_CORRECTION,
    CUSTOM_STOCK_DISTRIBUTION,
    EQUITY_RIGHTS,
    SCRIP_STOCK_DIVIDENDS,
    STOCK_DIVIDENDS,
    STOCK_ACQUISITION,
    CASH_AND_STOCK_ACQUISITION,
    SPIN_OFF
}